name: Lab01 Variables and Secrets
run-name: Lab01 - ${{ github.actor }} is testing variables and secrets 🚀
permissions: read-all
on:
  workflow_dispatch:
env:
  MY_VARIABLE: Hello, GitHub Actions!
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run hello world
        run: echo "🎉 Step of the job is running on ${{ runner.os }}!"
      - name: Print workflow variable
        run: echo "$MY_VARIABLE"
      - name: Print environment secret
        env:
          demo_secret: ${{ secrets.DEMO_SECRET }}
        run: echo a "$DEMO_SECRET" b

