name: Lab02 Reuse and Artifacts
run-name: Lab02 - ${{ github.actor }} is calling Composite Actions 🚀
permissions: read-all
on:
  workflow_dispatch:
jobs:
  composite-action-job:
    runs-on: ubuntu-latest
    name: Example of composite action - build DOTNET app
    steps:
      - uses: ./.github/actions/build-dotnet-app
        with:
          folder-path: 'apps/uptodate-app'
#  reusable-workflow-job:

