name: Lab10 SCA
run-name: Lab10 - ${{ github.actor }} is finding vulns🚀
permissions: read-all
# Set your preferences for the script
defaults:
  run:
    shell: pwsh
on:
  # Make it possible to other workflows to call this
  workflow_call:
  # Make it possible to manually run this workflow
  workflow_dispatch:
  # Dependency review is meant to work with prs
  pull_request:
jobs:
  Test-Vulnerabilities-With-Dependency-Check:
    name: OWASP Dependency Check
    runs-on: ubuntu-latest
    # Steps to actually build the application
    steps:
      # Check out the git repository
      - name: Checkout
        uses: actions/checkout@v4
      # Ensure proper version of .NET
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"
      # Ensure this to make sure to actually test against real deal
      - name: Install .NET dependencies
        run: dotnet restore
      # Sometimes (even when considered as a bad practice) part of the dependencies are fetched during build, so better to build first
      - name: Build application
        run: dotnet build
      # Run OWASP Dependency check
      - name: Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: "ci-security"
          path: "."
          format: "HTML"
          out: "reports" # this is the default, no need to specify unless you wish to override it
          args: >
            --failOnCVSS 7
            --enableRetired
      # Use always() to ensure that even if the above fails on threshold the results are uploaded
      - name: Upload Test results
        uses: actions/upload-artifact@master
        if: ${{ always() }}
        with:
          name: OWASP Dependency Check report
          path: ${{github.workspace}}/reports
