# Name of the workflow
name: Lab22 Secret scanning
# How the workflow run is named in GitHub
run-name: Lab22 - ${{ github.actor }} is looking for keys 🔑
permissions: read-all
on:
  # Make it possible to other workflows to call this
  workflow_call:
  # Make it possible to manually run this workflow
  workflow_dispatch:
jobs:
  secret-scanning-with-gitleaks:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  secret-scanning-with-trufflehog:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Secret Scanning
        uses: trufflesecurity/trufflehog@main
        with:
          # Note that verified means the secret is known to be valid, so the secrets in this repo won't be flagged
          extra_args: --results=verified,unverified,unknown
